//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GurpsCharacterEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GurpsCharacterEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutWindow {
            get {
                return ResourceManager.GetString("AboutWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string AboutWindowClose {
            get {
                return ResourceManager.GetString("AboutWindowClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advantages/disadvantages:.
        /// </summary>
        public static string CharacterSheetAdvantages {
            get {
                return ResourceManager.GetString("CharacterSheetAdvantages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Lift:.
        /// </summary>
        public static string CharacterSheetBasicLift {
            get {
                return ResourceManager.GetString("CharacterSheetBasicLift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Move:.
        /// </summary>
        public static string CharacterSheetBasicMove {
            get {
                return ResourceManager.GetString("CharacterSheetBasicMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Speed:.
        /// </summary>
        public static string CharacterSheetBasicSpeed {
            get {
                return ResourceManager.GetString("CharacterSheetBasicSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dexterity:.
        /// </summary>
        public static string CharacterSheetDexterity {
            get {
                return ResourceManager.GetString("CharacterSheetDexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health:.
        /// </summary>
        public static string CharacterSheetHealth {
            get {
                return ResourceManager.GetString("CharacterSheetHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence:.
        /// </summary>
        public static string CharacterSheetIntelligence {
            get {
                return ResourceManager.GetString("CharacterSheetIntelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory:.
        /// </summary>
        public static string CharacterSheetInventory {
            get {
                return ResourceManager.GetString("CharacterSheetInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No picture.
        /// </summary>
        public static string CharacterSheetNoPicture {
            get {
                return ResourceManager.GetString("CharacterSheetNoPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perception:.
        /// </summary>
        public static string CharacterSheetPerception {
            get {
                return ResourceManager.GetString("CharacterSheetPerception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills:.
        /// </summary>
        public static string CharacterSheetSkills {
            get {
                return ResourceManager.GetString("CharacterSheetSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength:.
        /// </summary>
        public static string CharacterSheetStrength {
            get {
                return ResourceManager.GetString("CharacterSheetStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willpower:.
        /// </summary>
        public static string CharacterSheetWillpower {
            get {
                return ResourceManager.GetString("CharacterSheetWillpower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unnamed character).
        /// </summary>
        public static string UnnamedCharacter {
            get {
                return ResourceManager.GetString("UnnamedCharacter", resourceCulture);
            }
        }
    }
}
