//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GurpsCharacterEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GurpsCharacterEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutWindow {
            get {
                return ResourceManager.GetString("AboutWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string AboutWindowClose {
            get {
                return ResourceManager.GetString("AboutWindowClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advantages/disadvantages:.
        /// </summary>
        public static string CharacterSheetAdvantages {
            get {
                return ResourceManager.GetString("CharacterSheetAdvantages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Lift:.
        /// </summary>
        public static string CharacterSheetBasicLift {
            get {
                return ResourceManager.GetString("CharacterSheetBasicLift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Move:.
        /// </summary>
        public static string CharacterSheetBasicMove {
            get {
                return ResourceManager.GetString("CharacterSheetBasicMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Speed:.
        /// </summary>
        public static string CharacterSheetBasicSpeed {
            get {
                return ResourceManager.GetString("CharacterSheetBasicSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dexterity:.
        /// </summary>
        public static string CharacterSheetDexterity {
            get {
                return ResourceManager.GetString("CharacterSheetDexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health:.
        /// </summary>
        public static string CharacterSheetHealth {
            get {
                return ResourceManager.GetString("CharacterSheetHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence:.
        /// </summary>
        public static string CharacterSheetIntelligence {
            get {
                return ResourceManager.GetString("CharacterSheetIntelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory:.
        /// </summary>
        public static string CharacterSheetInventory {
            get {
                return ResourceManager.GetString("CharacterSheetInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max FP:.
        /// </summary>
        public static string CharacterSheetMaxFP {
            get {
                return ResourceManager.GetString("CharacterSheetMaxFP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max HP:.
        /// </summary>
        public static string CharacterSheetMaxHP {
            get {
                return ResourceManager.GetString("CharacterSheetMaxHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No picture.
        /// </summary>
        public static string CharacterSheetNoPicture {
            get {
                return ResourceManager.GetString("CharacterSheetNoPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perception:.
        /// </summary>
        public static string CharacterSheetPerception {
            get {
                return ResourceManager.GetString("CharacterSheetPerception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills:.
        /// </summary>
        public static string CharacterSheetSkills {
            get {
                return ResourceManager.GetString("CharacterSheetSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength:.
        /// </summary>
        public static string CharacterSheetStrength {
            get {
                return ResourceManager.GetString("CharacterSheetStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character points:.
        /// </summary>
        public static string CharacterSheetTotalPoints {
            get {
                return ResourceManager.GetString("CharacterSheetTotalPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willpower:.
        /// </summary>
        public static string CharacterSheetWillpower {
            get {
                return ResourceManager.GetString("CharacterSheetWillpower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load file..
        /// </summary>
        public static string DialogLoadFailed {
            get {
                return ResourceManager.GetString("DialogLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string EditAdvantageName {
            get {
                return ResourceManager.GetString("EditAdvantageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points:.
        /// </summary>
        public static string EditAdvantagePoints {
            get {
                return ResourceManager.GetString("EditAdvantagePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit advantage/disadvantage.
        /// </summary>
        public static string EditAdvantageWindow {
            get {
                return ResourceManager.GetString("EditAdvantageWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string EditAdvantageWindowCancel {
            get {
                return ResourceManager.GetString("EditAdvantageWindowCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string EditAdvantageWindowOk {
            get {
                return ResourceManager.GetString("EditAdvantageWindowOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string EditItemDescription {
            get {
                return ResourceManager.GetString("EditItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string EditItemName {
            get {
                return ResourceManager.GetString("EditItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value:.
        /// </summary>
        public static string EditItemValue {
            get {
                return ResourceManager.GetString("EditItemValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight:.
        /// </summary>
        public static string EditItemWeight {
            get {
                return ResourceManager.GetString("EditItemWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit item.
        /// </summary>
        public static string EditItemWindow {
            get {
                return ResourceManager.GetString("EditItemWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string EditItemWindowCancel {
            get {
                return ResourceManager.GetString("EditItemWindowCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string EditItemWindowOk {
            get {
                return ResourceManager.GetString("EditItemWindowOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty:.
        /// </summary>
        public static string EditSkillDifficulty {
            get {
                return ResourceManager.GetString("EditSkillDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string EditSkillName {
            get {
                return ResourceManager.GetString("EditSkillName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative level:.
        /// </summary>
        public static string EditSkillRelativeLevel {
            get {
                return ResourceManager.GetString("EditSkillRelativeLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistic:.
        /// </summary>
        public static string EditSkillStat {
            get {
                return ResourceManager.GetString("EditSkillStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit skill.
        /// </summary>
        public static string EditSkillWindow {
            get {
                return ResourceManager.GetString("EditSkillWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string EditSkillWindowCancel {
            get {
                return ResourceManager.GetString("EditSkillWindowCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string EditSkillWindowOk {
            get {
                return ResourceManager.GetString("EditSkillWindowOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add advantage/disadvantage.
        /// </summary>
        public static string MenuAddAdvantage {
            get {
                return ResourceManager.GetString("MenuAddAdvantage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add item.
        /// </summary>
        public static string MenuAddItem {
            get {
                return ResourceManager.GetString("MenuAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add skill.
        /// </summary>
        public static string MenuAddSkill {
            get {
                return ResourceManager.GetString("MenuAddSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit primary stats.
        /// </summary>
        public static string MenuEditPrimaryStats {
            get {
                return ResourceManager.GetString("MenuEditPrimaryStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit secondary stats.
        /// </summary>
        public static string MenuEditSecondaryStats {
            get {
                return ResourceManager.GetString("MenuEditSecondaryStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit primary stats.
        /// </summary>
        public static string PrimaryStatsWindow {
            get {
                return ResourceManager.GetString("PrimaryStatsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string PrimaryStatsWindowOk {
            get {
                return ResourceManager.GetString("PrimaryStatsWindowOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string RibbonAppMenuItemOpen {
            get {
                return ResourceManager.GetString("RibbonAppMenuItemOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string RibbonAppMenuItemQuit {
            get {
                return ResourceManager.GetString("RibbonAppMenuItemQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string RibbonAppMenuItemSaveAs {
            get {
                return ResourceManager.GetString("RibbonAppMenuItemSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advantages/disadvantages.
        /// </summary>
        public static string RibbonGroupAdvantages {
            get {
                return ResourceManager.GetString("RibbonGroupAdvantages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string RibbonGroupInventory {
            get {
                return ResourceManager.GetString("RibbonGroupInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string RibbonGroupSkills {
            get {
                return ResourceManager.GetString("RibbonGroupSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string RibbonGroupStats {
            get {
                return ResourceManager.GetString("RibbonGroupStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character sheet.
        /// </summary>
        public static string RibbonTabCharacterSheet {
            get {
                return ResourceManager.GetString("RibbonTabCharacterSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit secondary stats.
        /// </summary>
        public static string SecondaryStatsWindow {
            get {
                return ResourceManager.GetString("SecondaryStatsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string SecondaryStatsWindowOk {
            get {
                return ResourceManager.GetString("SecondaryStatsWindowOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unnamed character).
        /// </summary>
        public static string UnnamedCharacter {
            get {
                return ResourceManager.GetString("UnnamedCharacter", resourceCulture);
            }
        }
    }
}
